USE PETCAREX
GO

--==============================================================
-- PHẦN 3: THIẾT LẬP CHỈ MỤC (INDEXES)
--==============================================================

CREATE UNIQUE INDEX IX_KHACH_HANG_SĐT ON KHACH_HANG(SoDienThoai);
CREATE UNIQUE INDEX IX_KHACH_HANG_CCCD ON KHACH_HANG(CCCD);
CREATE UNIQUE INDEX IX_HOA_DON_MaPhieuDichVu ON HOA_DON(MaPhieuDichVu, NgayLap);
CREATE INDEX IX_THU_CUNG_MaKH ON THU_CUNG(MaKhachHang);
CREATE INDEX IX_SAN_PHAM_TenSP ON SAN_PHAM(TenSanPham);
CREATE INDEX IX_VACXIN_TenVX ON VACXIN(TenVacxin);
CREATE INDEX IX_LO_HANG_HSD ON LO_HANG(HanSuDung);
CREATE INDEX IX_HOA_DON_NgayLap ON HOA_DON(NgayLap);
CREATE INDEX IX_DANH_GIA_DiemCL ON DANH_GIA(DiemChatLuongDichVu);
CREATE INDEX IX_CT_MUA_HANG_MaPDV ON CHI_TIET_MUA_HANG(MaPhieuDichVu);
CREATE INDEX IX_PHIEU_KHAM_MaTC ON PHIEU_KHAM_BENH(MaThuCung);
CREATE INDEX IX_LICH_HEN_CN_TG ON LICH_HEN(MaChiNhanh, ThoiGian);
CREATE INDEX IX_KHO_HANG_CN_SP ON KHO_HANG(MaChiNhanh, MaSanPham);
CREATE INDEX IX_HOA_DON_NV_Ngay ON HOA_DON(MaNhanVien, NgayLap);
CREATE INDEX IX_PHAN_LOAI_KH_Ma_Nam ON PHAN_LOAI_KHACH_HANG(MaKhachHang, Nam);
CREATE INDEX IX_NHAN_VIEN_CN_ChucVu ON NHAN_VIEN(MaChiNhanh, ChucVu);
CREATE INDEX IX_LS_DIEU_DONG_Ma_Ngay ON LICH_SU_DIEU_DONG(MaNhanVien, NgayBatDau);
CREATE INDEX IX_PHIEU_TIEM_Ma_Ngay ON PHIEU_TIEM_PHONG(MaThuCung, NgayTiem);
CREATE INDEX IX_TAI_KHOAN_TenDangNhap ON TAI_KHOAN(TenDangNhap);
GO